### ISSUE TITLE
[BUG] CentOS 7.6 build error

### ISSUE THREAD

**Issue by yueyihua** [etr/libhttpserver#203]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have checked that your issue isn't already filed: https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues

### Description

Build is broken with version 0.18.1

### Steps to Reproduce

1. Build with libmicrohttpd == 0.9.70

Expected behavior: Build finishes without errors.

Actual behavior: Build is broken

Reproduces how often: 100%

### Versions

OS version (linux - cross-compiled using buildroot)
libhttpserver version 0.18.1
libmicrohttpd version 0.9.70  - self-compiled

If you have problems during build:
* Compiler version
* autotools version

### Additional Information

../../src/httpserver/http_response.hpp:62:9: error: function ‘httpserver::http_response::http_response(httpserver::http_response&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘httpserver::http_response::http_response(httpserver::http_response&&)’
         http_response(http_response&& b) noexcept = default;
         ^
../../src/httpserver/http_response.hpp:65:24: error: function ‘httpserver::http_response& httpserver::http_response::operator=(httpserver::http_response&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘httpserver::http_response& httpserver::http_response::operator=(httpserver::http_response&&)’
         http_response& operator=(http_response&& b) noexcept = default;
                        ^
In file included from ../../src/httpserver/details/modded_request.hpp:28:0,
                 from ../../src/webserver.cpp:64:
../../src/httpserver/http_request.hpp:234:9: error: function ‘httpserver::http_request::http_request(httpserver::http_request&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘httpserver::http_request::http_request(httpserver::http_request&&)’
         http_request(http_request&& b) noexcept = default;
         ^
In file included from ../../src/webserver.cpp:66:0:
../../src/httpserver/http_resource.hpp:220:9: error: function ‘httpserver::http_resource::http_resource(httpserver::http_resource&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘httpserver::http_resource::http_resource(httpserver::http_resource&&)’
         http_resource(http_resource&& b) noexcept = default;
         ^
In file included from ../../src/webserver.cpp:69:0:
../../src/httpserver/string_response.hpp:49:9: error: function ‘httpserver::string_response::string_response(httpserver::string_response&&)’ defaulted on its first declaration with an exception-specification that differs from the implicit declaration ‘httpserver::string_response::string_response(httpserver::string_response&&)’
         string_response(string_response&& other) noexcept = default;

**Comment by beneschtech** [comment]
Use https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/

The stock compiler on Cent 7 is gcc 4.8 which is barely c++11 capable.

On Tue, 2020-08-04 at 20:25 -0700, yueyihua wrote:
> 
> 
> 
> Prerequisites
> 
> 
>  Put an X between the brackets on this line if you have checked that
> your issue isn't already filed: 
> https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues
> 
> Description
> 
> Build is broken with version 0.18.1
> 
> Steps to Reproduce
> 
> 
> Build with libmicrohttpd == 0.9.70
> 
> Expected behavior: Build finishes without errors.
> 
> Actual behavior: Build is broken
> 
> Reproduces how often: 100%
> 
> Versions
> 
> OS version (linux - cross-compiled using buildroot)
> 
> libhttpserver version 0.18.1
> 
> libmicrohttpd version 0.9.70  - self-compiled
> 
> If you have problems during build:
> 
> 
> Compiler version
> autotools version
> 
> Additional Information
> 
> ../../src/httpserver/http_response.hpp:62:9: error: function
> ‘httpserver::http_response::http_response(httpserver::http_response&&
> )’ defaulted on its first declaration with an exception-specification 
> that differs from the implicit declaration
> ‘httpserver::http_response::http_response(httpserver::http_response&&
> )’
> 
> http_response(http_response&& b) noexcept = default;
> 
> ^
> 
> ../../src/httpserver/http_response.hpp:65:24: error: function
> ‘httpserver::http_response&
> httpserver::http_response::operator=(httpserver::http_response&&)’
> defaulted on its first declaration with an exception-specification
> that differs from the implicit declaration
> ‘httpserver::http_response&
> httpserver::http_response::operator=(httpserver::http_response&&)’
> 
> http_response& operator=(http_response&& b) noexcept = default;
> 
> ^
> 
> In file included from
> ../../src/httpserver/details/modded_request.hpp:28:0,
> 
> from ../../src/webserver.cpp:64:
> 
> ../../src/httpserver/http_request.hpp:234:9: error: function
> ‘httpserver::http_request::http_request(httpserver::http_request&&)’
> defaulted on its first declaration with an exception-specification
> that differs from the implicit declaration
> ‘httpserver::http_request::http_request(httpserver::http_request&&)’
> 
> http_request(http_request&& b) noexcept = default;
> 
> ^
> 
> In file included from ../../src/webserver.cpp:66:0:
> 
> ../../src/httpserver/http_resource.hpp:220:9: error: function
> ‘httpserver::http_resource::http_resource(httpserver::http_resource&&
> )’ defaulted on its first declaration with an exception-specification 
> that differs from the implicit declaration
> ‘httpserver::http_resource::http_resource(httpserver::http_resource&&
> )’
> 
> http_resource(http_resource&& b) noexcept = default;
> 
> ^
> 
> In file included from ../../src/webserver.cpp:69:0:
> 
> ../../src/httpserver/string_response.hpp:49:9: error: function
> ‘httpserver::string_response::string_response(httpserver::string_resp
> onse&&)’ defaulted on its first declaration with an exception-
> specification that differs from the implicit declaration
> ‘httpserver::string_response::string_response(httpserver::string_resp
> onse&&)’
> 
> string_response(string_response&& other) noexcept = default;
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "https://github.com/etr/libhttpserver/issues/203",
> "url": "https://github.com/etr/libhttpserver/issues/203",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
-- 
Chris Benesch <chris@beneschtech.com>

**Comment by etr** [comment]
Agree with the above. The issue seems to be an old compiler. I would recommend using a version of GCC that is at least 5.5.0.
Sorry for the documentation to be misleading and referencing an older version (fixing that).

Can you retry as suggested above and let me know if that solves?

**Comment by yueyihua** [comment]
@etr yes, the problem was solved after the using new gcc version.
In addition, i have registered a service using libhttpserver, but i don't know how to process my json body using postman. can you shou me an example? thanks!

**Comment by etr** [comment]
I am not familiar with postman. In libhttpserver you can fetch the content of an http_request by just using the get_content method on the request itself - as I don't know postman, I am not sure of how you would pass the content over
